/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as WalletsRouteImport } from './routes/wallets'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletsRoute = WalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/profile': typeof ProfileRoute
  '/wallets': typeof WalletsRoute
}
export interface FileRoutesByTo {
  '/profile': typeof ProfileRoute
  '/wallets': typeof WalletsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/profile': typeof ProfileRoute
  '/wallets': typeof WalletsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/profile' | '/wallets'
  fileRoutesByTo: FileRoutesByTo
  to: '/profile' | '/wallets'
  id: '__root__' | '/profile' | '/wallets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProfileRoute: typeof ProfileRoute
  WalletsRoute: typeof WalletsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallets': {
      id: '/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof WalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ProfileRoute: ProfileRoute,
  WalletsRoute: WalletsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
